name: Online Learning Pipeline

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Inject GCP Credentials
        run: echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json

      - name: Download Model
        run: python src/download_from_drive.py

      - name: Train Model
        run: python src/online_train.py

      - name: Upload Model
        run: python src/upload_to_drive.py
